version: "3.8"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auconchegante
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./java-services/auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./java-services:/workspace/app
      - ./java-services/auth/src/main/resources/application.yml:/workspace/app/auth/src/main/resources/application.yml
      - maven_cache:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auconchegante
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    working_dir: /workspace/app/auth
    depends_on:
      - db

volumes:
  maven_cache:
  postgres_data:
