version: "3.8"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auconchegante
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # auth-service:
  #   image: maven:3.9-openjdk-21
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./java-services:/workspace/app
  #     - maven_cache:/root/.m2
  #   working_dir: /workspace/app/auth
  #   command: mvn spring-boot:run
  #   depends_on:
  #     - db

volumes:
  maven_cache:
  postgres_data:
