version: "3.8"

services:
  auth-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - auth-network

  booking-db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=booking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    networks:
      - booking-network

  auth-api:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - auth-network
    volumes:
      - .:/workspace/app
      - ./auth/src/main/resources/application.yml:/workspace/app/auth/src/main/resources/application.yml
      - maven_cache:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    working_dir: /workspace/app/auth
    depends_on:
      - auth-db

volumes:
  maven_cache:
  auth_db_data:
  booking_db_data:

networks:
  auth-network:
    driver: bridge
  booking-network:
    driver: bridge
